// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {models} from '../models';
import {config} from '../models';
import {context} from '../models';

export function AddDownload(arg1:api.AddDownloadRequest):Promise<api.AddDownloadResponse>;

export function CancelDownload(arg1:number):Promise<void>;

export function CreateQueue(arg1:api.CreateQueueRequest):Promise<api.CreateQueueResponse>;

export function DeleteDownload(arg1:number):Promise<void>;

export function DeleteQueue(arg1:number):Promise<void>;

export function GetAllQueueStats():Promise<Array<api.QueueStats>>;

export function GetDownload(arg1:number):Promise<models.DownloadItem>;

export function GetDownloadInfo(arg1:string,arg2:Record<string, string>):Promise<api.DownloadInfoResponse>;

export function GetDownloadStats():Promise<api.DownloadStats>;

export function GetDownloads():Promise<Array<models.DownloadItem>>;

export function GetQueue(arg1:number):Promise<models.QueueModel>;

export function GetQueueStats(arg1:number):Promise<api.QueueStatsResponse>;

export function GetQueues():Promise<Array<models.QueueModel>>;

export function GetSettings():Promise<config.Settings>;

export function GetSystemInfo():Promise<Record<string, any>>;

export function Greet(arg1:string):Promise<string>;

export function OpenDownloadFolder(arg1:number):Promise<void>;

export function PauseDownload(arg1:number):Promise<void>;

export function PauseQueue(arg1:number):Promise<void>;

export function ResumeDownload(arg1:number):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function StartDownload(arg1:number):Promise<void>;

export function StartQueue(arg1:number):Promise<void>;

export function StopQueue(arg1:number):Promise<void>;

export function UpdateQueue(arg1:api.UpdateQueueRequest):Promise<void>;

export function UpdateSettings(arg1:config.Settings):Promise<void>;
