// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDownload(arg1) {
  return window['go']['main']['App']['AddDownload'](arg1);
}

export function CancelDownload(arg1) {
  return window['go']['main']['App']['CancelDownload'](arg1);
}

export function CreateQueue(arg1) {
  return window['go']['main']['App']['CreateQueue'](arg1);
}

export function DeleteDownload(arg1) {
  return window['go']['main']['App']['DeleteDownload'](arg1);
}

export function DeleteQueue(arg1) {
  return window['go']['main']['App']['DeleteQueue'](arg1);
}

export function GetAllQueueStats() {
  return window['go']['main']['App']['GetAllQueueStats']();
}

export function GetDownload(arg1) {
  return window['go']['main']['App']['GetDownload'](arg1);
}

export function GetDownloadInfo(arg1, arg2) {
  return window['go']['main']['App']['GetDownloadInfo'](arg1, arg2);
}

export function GetDownloadStats() {
  return window['go']['main']['App']['GetDownloadStats']();
}

export function GetDownloads() {
  return window['go']['main']['App']['GetDownloads']();
}

export function GetQueue(arg1) {
  return window['go']['main']['App']['GetQueue'](arg1);
}

export function GetQueueStats(arg1) {
  return window['go']['main']['App']['GetQueueStats'](arg1);
}

export function GetQueues() {
  return window['go']['main']['App']['GetQueues']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenDownloadFolder(arg1) {
  return window['go']['main']['App']['OpenDownloadFolder'](arg1);
}

export function PauseDownload(arg1) {
  return window['go']['main']['App']['PauseDownload'](arg1);
}

export function PauseQueue(arg1) {
  return window['go']['main']['App']['PauseQueue'](arg1);
}

export function ResumeDownload(arg1) {
  return window['go']['main']['App']['ResumeDownload'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['main']['App']['Shutdown'](arg1);
}

export function StartDownload(arg1) {
  return window['go']['main']['App']['StartDownload'](arg1);
}

export function StartQueue(arg1) {
  return window['go']['main']['App']['StartQueue'](arg1);
}

export function StopQueue(arg1) {
  return window['go']['main']['App']['StopQueue'](arg1);
}

export function UpdateQueue(arg1) {
  return window['go']['main']['App']['UpdateQueue'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
